import os
import uuid

from datetime import date, datetime
from functools import wraps
from pathlib import Path

import psycopg
from psycopg.rows import dict_row
from psycopg.errors import UniqueViolation

from dotenv import load_dotenv

from flask import (
    Flask,
    flash,
    g,
    redirect,
    render_template,
    request,
    send_from_directory,
    session,
    url_for,
)

from werkzeug.security import (
    check_password_hash,
    generate_password_hash,
)

from werkzeug.utils import secure_filename


# =========================================================
# CONFIGURATION
# =========================================================

load_dotenv()

ROOT = Path(__file__).resolve().parent

app = Flask(__name__)

app.config.update(
    SECRET_KEY=os.getenv(
        "VIDELINA_SECRET_KEY",
        "change-this-secret-before-production"
    ),

    LIBRARY_FOLDER=ROOT / "private_library",

    MAX_CONTENT_LENGTH=20 * 1024 * 1024,
)


ALLOWED_LIBRARY_EXTENSIONS = {
    "pdf",
    "epub",
}

ALLOWED_NEWS_IMAGE_EXTENSIONS = {
    "jpg",
    "jpeg",
    "png",
    "webp",
}

NEWS_IMAGE_FOLDER = ROOT / "static" / "news"

app.config["NEWS_IMAGE_FOLDER"] = NEWS_IMAGE_FOLDER
app.config["MAX_CONTENT_LENGTH"] = 20 * 1024 * 1024

# =========================================================
# POSTGRESQL
# =========================================================

def db():

    if "db" not in g:

        database_url = os.getenv("DATABASE_URL")

        if database_url:
            g.db = psycopg.connect(
                database_url,
                row_factory=dict_row,
            )

        else:
            g.db = psycopg.connect(
                host=os.getenv("DB_HOST", "localhost"),
                port=os.getenv("DB_PORT", "5432"),
                dbname=os.getenv("DB_NAME", "videlina_db"),
                user=os.getenv("DB_USER", "postgres"),
                password=os.getenv("DB_PASSWORD"),
                row_factory=dict_row,
            )

    return g.db


@app.teardown_appcontext
def close_db(_error=None):

    database = g.pop("db", None)

    if database is not None:
        database.close()


# =========================================================
# INITIALISATION DES TABLES
# =========================================================

@app.before_request
def initialise():

    database = db()

    database.execute("""
        CREATE TABLE IF NOT EXISTS members (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'Membre',
            status TEXT NOT NULL DEFAULT 'Actif'
        )
    """)

    database.execute("""
        CREATE TABLE IF NOT EXISTS meetings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            meeting_date TEXT NOT NULL,
            location TEXT NOT NULL,
            notes TEXT
        )
    """)

    database.execute("""
        CREATE TABLE IF NOT EXISTS documents (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            category TEXT NOT NULL,
            reference TEXT NOT NULL
        )
    """)

    database.execute("""
        CREATE TABLE IF NOT EXISTS library_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            author TEXT,
            category TEXT NOT NULL,
            description TEXT,
            stored_name TEXT NOT NULL,
            original_name TEXT NOT NULL,
            file_extension TEXT NOT NULL,
            added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    database.execute("""
        CREATE TABLE IF NOT EXISTS news (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            category TEXT NOT NULL,
            excerpt TEXT,
            content TEXT NOT NULL,
            image_name TEXT,
            status TEXT NOT NULL DEFAULT 'Brouillon',
            published_at TIMESTAMP,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
    """)

    database.commit()

    app.config["LIBRARY_FOLDER"].mkdir(
        parents=True,
        exist_ok=True
    )

    app.config["NEWS_IMAGE_FOLDER"].mkdir(
        parents=True,
        exist_ok=True
    )

# =========================================================
# AUTHENTIFICATION
# =========================================================

def login_required(view):

    @wraps(view)
    def wrapper(*args, **kwargs):

        if "member_id" not in session:

            flash(
                "Veuillez vous connecter.",
                "error"
            )

            return redirect(url_for("login"))

        return view(*args, **kwargs)

    return wrapper


def admin_required(view):

    @wraps(view)
    def wrapper(*args, **kwargs):

        if session.get("member_role") != "Administrateur":

            flash(
                "Action réservée aux administrateurs.",
                "error"
            )

            return redirect(url_for("dashboard"))

        return view(*args, **kwargs)

    return wrapper


# =========================================================
# ACCUEIL
# =========================================================

@app.get("/")
def home():

    database = db()

    news = database.execute(
        """
        SELECT *
        FROM news
        WHERE status = 'Publié'
        ORDER BY published_at DESC, created_at DESC
        LIMIT 3
        """
    ).fetchall()

    return render_template(
        "index.html",
        news=news
    )

# =========================================================
# CONTACT
# =========================================================

@app.post("/contact")
def contact():

    values = [
        request.form.get(key, "").strip()
        for key in (
            "name",
            "email",
            "subject",
            "message"
        )
    ]

    return render_template(
        "index.html",
        sent=all(values),
        form=request.form
    )


# =========================================================
# PREMIÈRE INSTALLATION
# =========================================================

@app.route("/setup", methods=["GET", "POST"])
def setup():

    if db().execute(
        "SELECT COUNT(*) AS total FROM members"
    ).fetchone()["total"]:

        return redirect(url_for("login"))

    if request.method == "POST":

        name = request.form.get(
            "name",
            ""
        ).strip()

        email = request.form.get(
            "email",
            ""
        ).strip().lower()

        password = request.form.get(
            "password",
            ""
        )

        confirm_password = request.form.get(
            "confirm_password",
            ""
        )

        if not name or not email or len(password) < 10:

            flash(
                "Indiquez un nom, un e-mail et un mot de passe d'au moins 10 caractères.",
                "error"
            )

        elif password != confirm_password:

            flash(
                "Les deux mots de passe ne correspondent pas.",
                "error"
            )

        else:

            try:

                db().execute(
                    """
                    INSERT INTO members
                    (
                        name,
                        email,
                        password_hash,
                        role
                    )
                    VALUES (%s, %s, %s, %s)
                    """,
                    (
                        name,
                        email,
                        generate_password_hash(password),
                        "Administrateur"
                    )
                )

                db().commit()

                flash(
                    "Administrateur créé. Vous pouvez vous connecter.",
                    "success"
                )

                return redirect(url_for("login"))

            except UniqueViolation:

                db().rollback()

                flash(
                    "Cette adresse e-mail est déjà utilisée.",
                    "error"
                )

    return render_template("setup.html")


# =========================================================
# CONNEXION
# =========================================================

@app.route("/connexion", methods=["GET", "POST"])
def login():

    if not db().execute(
        "SELECT COUNT(*) AS total FROM members"
    ).fetchone()["total"]:

        return redirect(url_for("setup"))

    if request.method == "POST":

        email = request.form.get(
            "email",
            ""
        ).strip().lower()

        password = request.form.get(
            "password",
            ""
        )

        member = db().execute(
            """
            SELECT *
            FROM members
            WHERE email = %s
            """,
            (email,)
        ).fetchone()

        if (
            member
            and member["status"] == "Actif"
            and check_password_hash(
                member["password_hash"],
                password
            )
        ):

            session.clear()

            session.update(
                member_id=member["id"],
                member_name=member["name"],
                member_role=member["role"]
            )

            return redirect(url_for("dashboard"))

        flash(
            "Adresse e-mail, mot de passe incorrect ou compte inactif.",
            "error"
        )

    return render_template("login.html")

# =========================================================
# CHANGEMENT DE MOT DE PASSE
# =========================================================

@app.route("/mot-de-passe", methods=["GET", "POST"])
@login_required
def change_password():

    if request.method == "POST":

        ancien_mot_de_passe = request.form.get(
            "ancien_mot_de_passe",
            ""
        )

        nouveau_mot_de_passe = request.form.get(
            "nouveau_mot_de_passe",
            ""
        )

        confirmation = request.form.get(
            "confirmation",
            ""
        )

        # Récupération du membre connecté
        member = db().execute(
            """
            SELECT password_hash
            FROM members
            WHERE id = %s
            """,
            (session["member_id"],)
        ).fetchone()

        if not member:
            flash(
                "Membre introuvable.",
                "error"
            )

            return redirect(
                url_for("dashboard")
            )

        # Vérification de l'ancien mot de passe
        if not check_password_hash(
            member["password_hash"],
            ancien_mot_de_passe
        ):
            flash(
                "Votre ancien mot de passe est incorrect.",
                "error"
            )

            return render_template(
                "change_password.html"
            )

        # Vérification de la longueur
        if len(nouveau_mot_de_passe) < 8:
            flash(
                "Le nouveau mot de passe doit contenir au moins 8 caractères.",
                "error"
            )

            return render_template(
                "change_password.html"
            )

        # Vérification de la confirmation
        if nouveau_mot_de_passe != confirmation:
            flash(
                "Les deux nouveaux mots de passe ne correspondent pas.",
                "error"
            )

            return render_template(
                "change_password.html"
            )

        # Nouveau hash sécurisé
        nouveau_hash = generate_password_hash(
            nouveau_mot_de_passe
        )

        db().execute(
            """
            UPDATE members
            SET password_hash = %s
            WHERE id = %s
            """,
            (
                nouveau_hash,
                session["member_id"]
            )
        )

        db().commit()

        flash(
            "Votre mot de passe a été modifié avec succès.",
            "success"
        )

        return redirect(
            url_for("dashboard")
        )

    return render_template(
        "change_password.html"
    )

# =========================================================
# DÉCONNEXION
# =========================================================

@app.get("/deconnexion")
def logout():

    session.clear()

    return redirect(url_for("home"))


# =========================================================
# TABLEAU DE BORD
# =========================================================

@app.get("/membres")
@login_required
def dashboard():

    database = db()

    counts = {

        "members": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM members
            WHERE status = 'Actif'
            """
        ).fetchone()["total"],

        "meetings": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM meetings
            WHERE meeting_date >= %s
            """,
            (date.today().isoformat(),)
        ).fetchone()["total"],

        "documents": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM documents
            """
        ).fetchone()["total"],

        "library": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM library_items
            """
        ).fetchone()["total"],

        "news": database.execute(
           """
           SELECT COUNT(*) AS total
           FROM news
         """
         ).fetchone()["total"],
    }

    return render_template(
        "dashboard.html",

        counts=counts,

        meetings=database.execute(
            """
            SELECT *
            FROM meetings
            ORDER BY meeting_date
            LIMIT 6
            """
        ).fetchall(),

        documents=database.execute(
            """
            SELECT *
            FROM documents
            ORDER BY title
            LIMIT 6
            """
        ).fetchall()
    )

# =========================================================
# GESTION DES MEMBRES
# =========================================================

@app.route(
    "/membres/gestion",
    methods=["GET", "POST"]
)
@login_required
@admin_required
def manage_members():

    if request.method == "POST":

        name = request.form.get(
            "name",
            ""
        ).strip()

        email = request.form.get(
            "email",
            ""
        ).strip().lower()

        role = request.form.get(
            "role",
            "Membre"
        ).strip()

        grade = request.form.get(
            "grade",
            "Apprenti"
        ).strip()

        password = request.form.get(
            "password",
            ""
        )

        # -------------------------------------------------
        # VALIDATION DU GRADE
        # -------------------------------------------------

        allowed_grades = (
            "Apprenti",
            "Compagnon",
            "Maître",
            "Maître Secret",
            "Grand Elu, Parfait et Sublime Macon",
            "Chevalier Rose-Croix",
            "CKS"
        )

        if grade not in allowed_grades:
            grade = "Apprenti"

        # -------------------------------------------------
        # VALIDATION
        # -------------------------------------------------

        if not name or not email or len(password) < 8:

            flash(
                "Indiquez le nom, l'e-mail et un mot de passe provisoire d'au moins 8 caractères.",
                "error"
            )

        else:

            try:

                db().execute(
                    """
                    INSERT INTO members
                    (
                        name,
                        email,
                        password_hash,
                        role,
                        grade
                    )
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    (
                        name,
                        email,
                        generate_password_hash(password),
                        role,
                        grade
                    )
                )

                db().commit()

                flash(
                    "Membre ajouté.",
                    "success"
                )

            except UniqueViolation:

                db().rollback()

                flash(
                    "Cette adresse e-mail est déjà utilisée.",
                    "error"
                )

    return render_template(
        "members.html",
        members=db().execute(
            """
            SELECT
                id,
                name,
                email,
                role,
                grade,
                status
            FROM members
            ORDER BY name
            """
        ).fetchall()
    )

# =========================================================
# ACTIVATION / DÉSACTIVATION
# =========================================================

# =========================================================
# ACTIVATION / DÉSACTIVATION
# =========================================================

@app.post("/membres/<int:member_id>/statut")
@login_required
@admin_required
def toggle_member_status(member_id):

    database = db()

    member = database.execute(
        """
        SELECT status
        FROM members
        WHERE id = %s
        """,
        (member_id,)
    ).fetchone()

    if (
        member
        and member_id != session["member_id"]
    ):

        new_status = (
            "Inactif"
            if member["status"] == "Actif"
            else "Actif"
        )

        database.execute(
            """
            UPDATE members
            SET status = %s
            WHERE id = %s
            """,
            (
                new_status,
                member_id
            )
        )

        database.commit()

    return redirect(
        url_for("manage_members")
    )


# =========================================================
# MODIFICATION DU GRADE D'UN MEMBRE
# =========================================================

@app.post("/membres/<int:member_id>/grade")
@login_required
@admin_required
def update_member_grade(member_id):

    grade = request.form.get(
        "grade",
        "Apprenti"
    ).strip()

    allowed_grades = (
        "Apprenti",
        "Compagnon",
        "Maître",
        "Maître Secret",
        "Grand Elu, Parfait et Sublime Maçon",
        "Chevalier Rose-Croix",
        "CKS"
    )

    if grade not in allowed_grades:

        flash(
            "Grade invalide.",
            "error"
        )

        return redirect(
            url_for("manage_members")
        )

    database = db()

    member = database.execute(
        """
        SELECT id
        FROM members
        WHERE id = %s
        """,
        (member_id,)
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error"
        )

        return redirect(
            url_for("manage_members")
        )

    # -------------------------------------------------
    # MISE À JOUR DU GRADE
    # -------------------------------------------------

    database.execute(
        """
        UPDATE members
        SET grade = %s
        WHERE id = %s
        """,
        (
            grade,
            member_id
        )
    )

    database.commit()

    flash(
        "Grade du membre mis à jour.",
        "success"
    )

    return redirect(
        url_for("manage_members")
    )

    # =========================================================
# MODIFICATION DE LA FONCTION D'UN MEMBRE
# =========================================================

@app.post("/membres/<int:member_id>/fonction")
@login_required
@admin_required
def update_member_role(member_id):

    role = request.form.get(
        "role",
        "Membre"
    ).strip()

    allowed_roles = (
        "Membre",
        "Officier",
        "Administrateur"
    )

    if role not in allowed_roles:

        flash(
            "Fonction invalide.",
            "error"
        )

        return redirect(
            url_for("manage_members")
        )

    database = db()

    member = database.execute(
        """
        SELECT id
        FROM members
        WHERE id = %s
        """,
        (member_id,)
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error"
        )

        return redirect(
            url_for("manage_members")
        )

    database.execute(
        """
        UPDATE members
        SET role = %s
        WHERE id = %s
        """,
        (
            role,
            member_id
        )
    )

    database.commit()

    flash(
        "Fonction du membre modifiée avec succès.",
        "success"
    )

    return redirect(
        url_for("manage_members")
    )

# =========================================================
# RÉUNIONS
# =========================================================

@app.route(
    "/reunions",
    methods=["GET", "POST"]
)
@login_required
def manage_meetings():

    if (
        request.method == "POST"
        and session.get("member_role") == "Administrateur"
    ):

        data = [
            request.form.get(
                key,
                ""
            ).strip()

            for key in (
                "title",
                "meeting_date",
                "location",
                "notes"
            )
        ]

        if all(data[:3]):

            db().execute(
                """
                INSERT INTO meetings
                (
                    title,
                    meeting_date,
                    location,
                    notes
                )
                VALUES (%s, %s, %s, %s)
                """,
                data
            )

            db().commit()

            flash(
                "Réunion enregistrée.",
                "success"
            )

    return render_template(
        "meetings.html",

        meetings=db().execute(
            """
            SELECT *
            FROM meetings
            ORDER BY meeting_date DESC
            """
        ).fetchall()
    )


# =========================================================
# DOCUMENTS
# =========================================================

@app.route(
    "/documents",
    methods=["GET", "POST"]
)
@login_required
def manage_documents():

    if (
        request.method == "POST"
        and session.get("member_role") == "Administrateur"
    ):

        data = [
            request.form.get(
                key,
                ""
            ).strip()

            for key in (
                "title",
                "category",
                "reference"
            )
        ]

        if all(data):

            db().execute(
                """
                INSERT INTO documents
                (
                    title,
                    category,
                    reference
                )
                VALUES (%s, %s, %s)
                """,
                data
            )

            db().commit()

            flash(
                "Référence ajoutée.",
                "success"
            )

    return render_template(
        "documents.html",

        documents=db().execute(
            """
            SELECT *
            FROM documents
            ORDER BY title
            """
        ).fetchall()
    )

# =========================================================
# MODIFIER UNE ACTUALITÉ
# =========================================================

@app.route("/admin/actualites/modifier/<int:news_id>", methods=["GET", "POST"])
@login_required
@admin_required
def edit_news(news_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM news
        WHERE id = %s
        """,
        (news_id,)
    ).fetchone()

    if item is None:

        flash(
            "Actualité introuvable.",
            "error"
        )

        return redirect(url_for("manage_news"))

    if request.method == "POST":

        title = request.form.get(
            "title",
            ""
        ).strip()

        category = request.form.get(
            "category",
            ""
        ).strip()

        excerpt = request.form.get(
            "excerpt",
            ""
        ).strip()

        content = request.form.get(
            "content",
            ""
        ).strip()

        status = request.form.get(
            "status",
            "Brouillon"
        ).strip()

        if status not in ("Brouillon", "Publié"):
            status = "Brouillon"

        if not title or not category or not content:

            flash(
                "Le titre, la catégorie et le contenu sont obligatoires.",
                "error"
            )

            return redirect(
                url_for(
                    "edit_news",
                    news_id=news_id
                )
            )

        # -------------------------------------------------
        # GESTION DE LA PUBLICATION
        # -------------------------------------------------

        if status == "Publié":

            published_at = (
                item["published_at"]
                or datetime.now()
            )

        else:

            published_at = None

        # -------------------------------------------------
        # IMAGE
        # -------------------------------------------------

        image = request.files.get("image")

        new_image_name = item["image_name"]
        new_image_path = None

        if image and image.filename:

            original_name = secure_filename(
                image.filename
            )

            if (
                not original_name
                or "." not in original_name
            ):

                flash(
                    "Nom de fichier image invalide.",
                    "error"
                )

                return redirect(
                    url_for(
                        "edit_news",
                        news_id=news_id
                    )
                )

            extension = (
                original_name
                .rsplit(".", 1)[-1]
                .lower()
            )

            if extension not in ALLOWED_NEWS_IMAGE_EXTENSIONS:

                flash(
                    "Format d'image non autorisé. "
                    "Utilisez JPG, JPEG, PNG ou WebP.",
                    "error"
                )

                return redirect(
                    url_for(
                        "edit_news",
                        news_id=news_id
                    )
                )

            new_image_name = (
                f"{uuid.uuid4().hex}.{extension}"
            )

            news_image_folder = (
                app.config["NEWS_IMAGE_FOLDER"]
            )

            news_image_folder.mkdir(
                parents=True,
                exist_ok=True
            )

            new_image_path = (
                news_image_folder
                / new_image_name
            )

            image.save(new_image_path)

        # -------------------------------------------------
        # MISE À JOUR
        # -------------------------------------------------

        try:

            database.execute(
                """
                UPDATE news
                SET
                    title = %s,
                    category = %s,
                    excerpt = %s,
                    content = %s,
                    image_name = %s,
                    status = %s,
                    published_at = %s,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                """,
                (
                    title,
                    category,
                    excerpt,
                    content,
                    new_image_name,
                    status,
                    published_at,
                    news_id
                )
            )

            database.commit()

        except Exception:

            database.rollback()

            if new_image_path and new_image_path.exists():
                new_image_path.unlink()

            raise

        # -------------------------------------------------
        # SUPPRIMER L'ANCIENNE IMAGE
        # -------------------------------------------------

        if (
            new_image_path
            and item["image_name"]
            and item["image_name"] != new_image_name
        ):

            old_image_path = (
                app.config["NEWS_IMAGE_FOLDER"]
                / item["image_name"]
            )

            if old_image_path.exists():
                old_image_path.unlink()

        flash(
            "Actualité modifiée avec succès.",
            "success"
        )

        return redirect(
            url_for("manage_news")
        )

    return render_template(
        "news_edit.html",
        item=item
    )


# =========================================================
# SUPPRIMER UNE ACTUALITÉ
# =========================================================

@app.post("/admin/actualites/supprimer/<int:news_id>")
@login_required
@admin_required
def delete_news(news_id):

    database = db()

    item = database.execute(
        """
        SELECT image_name
        FROM news
        WHERE id = %s
        """,
        (news_id,)
    ).fetchone()

    if item is None:

        flash(
            "Actualité introuvable.",
            "error"
        )

        return redirect(
            url_for("manage_news")
        )

    database.execute(
        """
        DELETE FROM news
        WHERE id = %s
        """,
        (news_id,)
    )

    database.commit()

    # -------------------------------------------------
    # SUPPRESSION DE L'IMAGE
    # -------------------------------------------------

    if item["image_name"]:

        image_path = (
            app.config["NEWS_IMAGE_FOLDER"]
            / item["image_name"]
        )

        if image_path.exists():
            image_path.unlink()

    flash(
        "Actualité supprimée avec succès.",
        "success"
    )

    return redirect(
        url_for("manage_news")
    )

# =========================================================
# ACTUALITÉS
# =========================================================

@app.route("/admin/actualites", methods=["GET", "POST"])
@login_required
@admin_required
def manage_news():

    database = db()

    if request.method == "POST":

        title = request.form.get(
            "title",
            ""
        ).strip()

        category = request.form.get(
            "category",
            ""
        ).strip()

        excerpt = request.form.get(
            "excerpt",
            ""
        ).strip()

        content = request.form.get(
            "content",
            ""
        ).strip()

        status = request.form.get(
            "status",
            "Brouillon"
        ).strip()

        if status not in ("Brouillon", "Publié"):
            status = "Brouillon"

        # =====================================================
        # VALIDATION
        # =====================================================

        if not title or not category or not content:

            flash(
                "Le titre, la catégorie et le contenu sont obligatoires.",
                "error"
            )

            return redirect(
                url_for("manage_news")
            )

        # =====================================================
        # IMAGE
        # =====================================================

        image = request.files.get("image")

        image_name = None
        image_path = None

        if image and image.filename:

            original_name = secure_filename(
                image.filename
            )

            if (
                not original_name
                or "." not in original_name
            ):

                flash(
                    "Nom de fichier image invalide.",
                    "error"
                )

                return redirect(
                    url_for("manage_news")
                )

            extension = (
                original_name
                .rsplit(".", 1)[-1]
                .lower()
            )

            if extension not in ALLOWED_NEWS_IMAGE_EXTENSIONS:

                flash(
                    "Format d'image non autorisé. "
                    "Utilisez JPG, JPEG, PNG ou WebP.",
                    "error"
                )

                return redirect(
                    url_for("manage_news")
                )

            image_name = (
                f"{uuid.uuid4().hex}.{extension}"
            )

            news_image_folder = (
                app.config["NEWS_IMAGE_FOLDER"]
            )

            news_image_folder.mkdir(
                parents=True,
                exist_ok=True
            )

            image_path = (
                news_image_folder
                / image_name
            )

            image.save(image_path)

        # =====================================================
        # PUBLICATION
        # =====================================================

        published_at = (
            datetime.now()
            if status == "Publié"
            else None
        )

        try:

            database.execute(
                """
                INSERT INTO news
                (
                    title,
                    category,
                    excerpt,
                    content,
                    image_name,
                    status,
                    published_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    title,
                    category,
                    excerpt,
                    content,
                    image_name,
                    status,
                    published_at
                )
            )

            database.commit()

        except Exception:

            database.rollback()

            if image_path and image_path.exists():
                image_path.unlink()

            raise

        flash(
            "Actualité enregistrée avec succès.",
            "success"
        )

        return redirect(
            url_for("manage_news")
        )

    # =====================================================
    # LISTE DES ACTUALITÉS
    # =====================================================

    news = database.execute(
        """
        SELECT *
        FROM news
        ORDER BY created_at DESC
        """
    ).fetchall()

    return render_template(
        "news_admin.html",
        news=news
    )

# =========================================================
# ACTUALITÉS PUBLIQUES
# =========================================================

@app.get("/actualites")
def public_news():

    database = db()

    news = database.execute(
        """
        SELECT *
        FROM news
        WHERE status = 'Publié'
        ORDER BY published_at DESC, created_at DESC
        """
    ).fetchall()

    return render_template(
        "news.html",
        news=news
    )


# =========================================================
# IMAGE D'UNE ACTUALITÉ
# =========================================================

@app.get("/actualites/image/<path:filename>")
def news_image(filename):

    return send_from_directory(
        app.config["NEWS_IMAGE_FOLDER"],
        filename,
        as_attachment=False
    )


# =========================================================
# DÉTAIL D'UNE ACTUALITÉ
# =========================================================

@app.get("/actualites/<int:news_id>")
def news_detail(news_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM news
        WHERE id = %s
        AND status = 'Publié'
        """,
        (news_id,)
    ).fetchone()

    if item is None:

        return render_template(
            "news_not_found.html"
        ), 404

    return render_template(
        "news_detail.html",
        item=item
    )

# =====================================================
# BIBLIOTHÈQUE
# =====================================================

@app.route(
    "/bibliotheque",
    methods=["GET", "POST"]
)
@login_required
def library():

    if request.method == "POST":

        if session.get("member_role") != "Administrateur":

            flash(
                "Seuls les administrateurs peuvent ajouter des ouvrages.",
                "error"
            )

            return redirect(
                url_for("library")
            )

        uploaded = request.files.get("file")

        title = request.form.get(
            "title",
            ""
        ).strip()

        author = request.form.get(
            "author",
            ""
        ).strip()

        category = request.form.get(
            "category",
            ""
        ).strip()

        description = request.form.get(
            "description",
            ""
        ).strip()

        access_grade = request.form.get(
            "access_grade",
            "Apprenti"
        ).strip()


        # =====================================================
        # VALIDATION DU GRADE
        # =====================================================

        allowed_grades = (
            "Apprenti",
            "Compagnon",
            "Maître",
            "Maître Secret",
            "Grand Elu, Parfait et Sublime Maçon",
            "Chevalier Rose-Croix",
            "CKS"
        )

        if access_grade not in allowed_grades:

            flash(
                "Niveau d'accès invalide.",
                "error"
            )

            return redirect(
                url_for("library")
            )


        # =====================================================
        # VALIDATION DU FICHIER
        # =====================================================

        if not uploaded or not uploaded.filename:

            flash(
                "Veuillez sélectionner un fichier.",
                "error"
            )

            return redirect(
                url_for("library")
            )

        original_name = secure_filename(
            uploaded.filename
        )

        if not original_name or "." not in original_name:

            flash(
                "Nom de fichier invalide.",
                "error"
            )

            return redirect(
                url_for("library")
            )

        extension = (
            original_name
            .rsplit(".", 1)[-1]
            .lower()
        )

        if extension not in ALLOWED_LIBRARY_EXTENSIONS:

            flash(
                "Format non autorisé. Utilisez uniquement PDF ou EPUB.",
                "error"
            )

            return redirect(
                url_for("library")
            )

        if not title or not category:

            flash(
                "Le titre et la catégorie sont obligatoires.",
                "error"
            )

            return redirect(
                url_for("library")
            )


        # =====================================================
        # ENREGISTREMENT DU FICHIER
        # =====================================================

        stored_name = (
            f"{uuid.uuid4().hex}.{extension}"
        )

        library_folder = (
            app.config["LIBRARY_FOLDER"]
        )

        library_folder.mkdir(
            parents=True,
            exist_ok=True
        )

        file_path = (
            library_folder
            / stored_name
        )

        uploaded.save(file_path)


        # =====================================================
        # ENREGISTREMENT EN BASE
        # =====================================================

        try:

            db().execute(
                """
                INSERT INTO library_items
                (
                    title,
                    author,
                    category,
                    description,
                    stored_name,
                    original_name,
                    file_extension,
                    access_grade
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    title,
                    author,
                    category,
                    description,
                    stored_name,
                    original_name,
                    extension,
                    access_grade
                )
            )

            db().commit()

        except Exception:

            db().rollback()

            if file_path.exists():
                file_path.unlink()

            raise


        flash(
            "Ouvrage ajouté à la bibliothèque privée.",
            "success"
        )

        return redirect(
            url_for("library")
        )


    # =====================================================
    # RECHERCHE DANS LA BIBLIOTHÈQUE
    # =====================================================

    search = request.args.get(
        "q",
        ""
    ).strip()


    if search:

        search_pattern = f"%{search}%"

        items = db().execute(
            """
            SELECT *
            FROM library_items
            WHERE
                title ILIKE %s
                OR author ILIKE %s
                OR category ILIKE %s
                OR description ILIKE %s
            ORDER BY added_at DESC
            """,
            (
                search_pattern,
                search_pattern,
                search_pattern,
                search_pattern
            )
        ).fetchall()

    else:

        items = db().execute(
            """
            SELECT *
            FROM library_items
            ORDER BY added_at DESC
            """
        ).fetchall()


    return render_template(
        "library.html",
        items=items,
        search=search
    )

# =====================================================
# MODIFICATION DU GRADE D'ACCÈS D'UN OUVRAGE
# =====================================================

@app.post("/bibliotheque/modifier-acces/<int:item_id>")
@login_required
@admin_required
def update_library_access(item_id):

    access_grade = request.form.get(
        "access_grade",
        "Apprenti"
    ).strip()

    allowed_grades = (
        "Apprenti",
        "Compagnon",
        "Maître",
        "Maître Secret",
        "Grand Elu, Parfait et Sublime Maçon",
        "Chevalier Rose-Croix",
        "CKS"
    )

    if access_grade not in allowed_grades:

        flash(
            "Niveau d'accès invalide.",
            "error"
        )

        return redirect(url_for("library"))

    database = db()

    item = database.execute(
        """
        SELECT id
        FROM library_items
        WHERE id = %s
        """,
        (item_id,)
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error"
        )

        return redirect(url_for("library"))

    database.execute(
        """
        UPDATE library_items
        SET access_grade = %s
        WHERE id = %s
        """,
        (
            access_grade,
            item_id
        )
    )

    database.commit()

    flash(
        "Niveau d'accès de l'ouvrage modifié avec succès.",
        "success"
    )

    return redirect(url_for("library"))

# =========================================================
# LECTURE D'UN OUVRAGE — ACCÈS PAR GRADE
# =========================================================

@app.get("/bibliotheque/lire/<int:item_id>")
@login_required
def read_library_item(item_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM library_items
        WHERE id = %s
        """,
        (item_id,)
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error"
        )

        return redirect(
            url_for("library")
        )

    # =====================================================
    # GRADE DU MEMBRE CONNECTÉ
    # =====================================================

    member = database.execute(
        """
        SELECT grade, role
        FROM members
        WHERE id = %s
        """,
        (session["member_id"],)
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error"
        )

        return redirect(
            url_for("library")
        )

    # =====================================================
    # HIÉRARCHIE DES GRADES
    # =====================================================

    grade_levels = {
        "Apprenti": 1,
        "Compagnon": 2,
        "Maître": 3,
        "Maître Secret": 4,
        "Grand Elu, Parfait et Sublime Macon": 5,
        "Chevalier Rose-Croix": 6,
        "CKS": 7
    }

    member_grade = (
        member["grade"] or "Apprenti"
    ).strip()

    required_grade = (
        item["access_grade"] or "Apprenti"
    ).strip()

    # =====================================================
    # ADMINISTRATEUR = ACCÈS COMPLET
    # =====================================================

    if member["role"] != "Administrateur":

        member_level = grade_levels.get(
            member_grade,
            0
        )

        required_level = grade_levels.get(
            required_grade,
            999
        )

        if member_level < required_level:

            flash(
                "Cet ouvrage est réservé à un grade supérieur.",
                "error"
            )

            return redirect(
                url_for("library")
            )

    # =====================================================
    # AUTORISÉ
    # =====================================================

    return render_template(
        "library_reader.html",
        item=item
    )

# =========================================================
# FICHIER PRIVÉ
# =========================================================

@app.get("/bibliotheque/fichier/<int:item_id>")
@login_required
def library_file(item_id):

    item = db().execute(
        """
        SELECT stored_name, original_name
        FROM library_items
        WHERE id = %s
        """,
        (item_id,)
    ).fetchone()

    if item is None:
        return "Ouvrage introuvable", 404

    return send_from_directory(
        app.config["LIBRARY_FOLDER"],
        item["stored_name"],
        as_attachment=False
    )


# =========================================================
# TÉLÉCHARGEMENT D'UN OUVRAGE
# =========================================================

@app.get("/bibliotheque/telecharger/<int:item_id>")
@login_required
def download_library_item(item_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM library_items
        WHERE id = %s
        """,
        (item_id,)
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error"
        )

        return redirect(
            url_for("library")
        )


    # =====================================================
    # ADMINISTRATEUR : ACCÈS COMPLET
    # =====================================================

    member = database.execute(
        """
        SELECT role, grade
        FROM members
        WHERE id = %s
        """,
        (session["member_id"],)
    ).fetchone()


    if member is None:

        flash(
            "Membre introuvable.",
            "error"
        )

        return redirect(
            url_for("library")
        )


    # =====================================================
    # HIÉRARCHIE DES GRADES
    # =====================================================

    grade_levels = {

        "Apprenti": 1,

        "Compagnon": 2,

        "Maître": 3,

        "Maître Secret": 4,

        "Grand Elu, Parfait et Sublime Maçon": 5,

        "Chevalier Rose-Croix": 6,

        "CKS": 7
    }


    member_grade = (
        member["grade"] or "Apprenti"
    ).strip()


    required_grade = (
        item["access_grade"] or "Apprenti"
    ).strip()


    # =====================================================
    # ADMINISTRATEUR : PAS DE RESTRICTION
    # =====================================================

    if member["role"] != "Administrateur":

        member_level = grade_levels.get(
            member_grade,
            0
        )

        required_level = grade_levels.get(
            required_grade,
            999
        )


        if member_level < required_level:

            flash(
                "Cet ouvrage est réservé à un grade supérieur.",
                "error"
            )

            return redirect(
                url_for("library")
            )


    # =====================================================
    # TÉLÉCHARGEMENT AUTORISÉ
    # =====================================================

    return send_from_directory(

        app.config["LIBRARY_FOLDER"],

        item["stored_name"],

        as_attachment=True,

        download_name=item["original_name"]
    )

# =========================================================
# SUPPRESSION D'UN OUVRAGE
# =========================================================

@app.post("/bibliotheque/supprimer/<int:item_id>")
@login_required
@admin_required
def delete_library_item(item_id):

    item = db().execute(
        """
        SELECT stored_name
        FROM library_items
        WHERE id = %s
        """,
        (item_id,)
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error"
        )

        return redirect(url_for("library"))

    file_path = (
        app.config["LIBRARY_FOLDER"]
        / item["stored_name"]
    )

    if file_path.exists():
        file_path.unlink()

    db().execute(
        """
        DELETE FROM library_items
        WHERE id = %s
        """,
        (item_id,)
    )

    db().commit()

    flash(
        "Ouvrage supprimé de la bibliothèque.",
        "success"
    )

    return redirect(url_for("library"))


# =========================================================
# LANCEMENT
# =========================================================

if __name__ == "__main__":

    app.run(
        debug=True
    )