# -*- coding: utf-8 -*-

import os
import uuid
import httpx

from datetime import date, datetime
from functools import wraps
from pathlib import Path

import psycopg
from psycopg.rows import dict_row
from psycopg.errors import UniqueViolation

from dotenv import load_dotenv
from supabase import create_client

from flask import (
    Flask,
    Response,
    flash,
    g,
    redirect,
    render_template,
    request,
    send_from_directory,
    session,
    url_for,
)

from werkzeug.security import (
    check_password_hash,
    generate_password_hash,
)

from werkzeug.utils import secure_filename


# =========================================================
# CONFIGURATION
# =========================================================

load_dotenv()

ROOT = Path(__file__).resolve().parent

app = Flask(__name__)


app.config.update(
    SECRET_KEY=os.getenv(
        "VIDELINA_SECRET_KEY",
        "change-this-secret-before-production"
    ),

    LIBRARY_FOLDER=ROOT / "private_library",

    NEWS_IMAGE_FOLDER=ROOT / "static" / "news",

    MAX_CONTENT_LENGTH=20 * 1024 * 1024,
)


# =========================================================
# CONSTANTES
# =========================================================

ALLOWED_LIBRARY_EXTENSIONS = {
    "pdf",
    "epub",
}

ALLOWED_NEWS_IMAGE_EXTENSIONS = {
    "jpg",
    "jpeg",
    "png",
    "webp",
}


ALLOWED_GRADES = (
    "Apprenti",
    "Compagnon",
    "Maître",
    "Maître Secret",
    "Grand Elu, Parfait et Sublime Maçon",
    "Chevalier Rose-Croix",
    "CKS",
)


ALLOWED_ROLES = (
    "Membre",
    "Officier",
    "Administrateur",
)


GRADE_LEVELS = {
    "Apprenti": 1,
    "Compagnon": 2,
    "Maître": 3,
    "Maître Secret": 4,
    "Grand Elu, Parfait et Sublime Maçon": 5,
    "Chevalier Rose-Croix": 6,
    "CKS": 7,
}


SUPABASE_LIBRARY_BUCKET = "library"


# =========================================================
# SUPABASE
# =========================================================

SUPABASE_URL = os.getenv("SUPABASE_URL")

SUPABASE_SERVICE_KEY = os.getenv(
    "SUPABASE_SERVICE_KEY"
)

supabase = None


if SUPABASE_URL and SUPABASE_SERVICE_KEY:

    supabase = create_client(
        SUPABASE_URL,
        SUPABASE_SERVICE_KEY,
    )


# =========================================================
# CONNEXION POSTGRESQL
# =========================================================

def db():

    if "db" not in g:

        database_url = os.getenv(
            "DATABASE_URL"
        )

        if database_url:

            g.db = psycopg.connect(
                database_url,
                row_factory=dict_row,
            )

        else:

            g.db = psycopg.connect(
                host=os.getenv(
                    "DB_HOST",
                    "localhost",
                ),

                port=os.getenv(
                    "DB_PORT",
                    "5432",
                ),

                dbname=os.getenv(
                    "DB_NAME",
                    "videlina_db",
                ),

                user=os.getenv(
                    "DB_USER",
                    "postgres",
                ),

                password=os.getenv(
                    "DB_PASSWORD",
                ),

                row_factory=dict_row,
            )

    return g.db


@app.teardown_appcontext
def close_db(_error=None):

    database = g.pop(
        "db",
        None,
    )

    if database is not None:
        database.close()


# =========================================================
# INITIALISATION DE LA BASE
# =========================================================

@app.before_request
def initialise():

    database = db()

    # -----------------------------------------------------
    # MEMBRES
    # -----------------------------------------------------

    database.execute(
        """
        CREATE TABLE IF NOT EXISTS members (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'Membre',
            status TEXT NOT NULL DEFAULT 'Actif',
            grade TEXT NOT NULL DEFAULT 'Apprenti'
        )
        """
    )

    database.execute(
        """
        ALTER TABLE members
        ADD COLUMN IF NOT EXISTS grade
        TEXT NOT NULL DEFAULT 'Apprenti'
        """
    )


    # -----------------------------------------------------
    # RÉUNIONS
    # -----------------------------------------------------

    database.execute(
        """
        CREATE TABLE IF NOT EXISTS meetings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            meeting_date TEXT NOT NULL,
            location TEXT NOT NULL,
            notes TEXT
        )
        """
    )


    # -----------------------------------------------------
    # DOCUMENTS
    # -----------------------------------------------------

    database.execute(
        """
        CREATE TABLE IF NOT EXISTS documents (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            category TEXT NOT NULL,
            reference TEXT NOT NULL
        )
        """
    )


    # -----------------------------------------------------
    # BIBLIOTHÈQUE
    # -----------------------------------------------------

    database.execute(
        """
        CREATE TABLE IF NOT EXISTS library_items (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            author TEXT,
            category TEXT NOT NULL,
            description TEXT,
            stored_name TEXT NOT NULL,
            original_name TEXT NOT NULL,
            file_extension TEXT NOT NULL,
            access_grade TEXT NOT NULL DEFAULT 'Apprenti',
            added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )

    database.execute(
        """
        ALTER TABLE library_items
        ADD COLUMN IF NOT EXISTS access_grade
        TEXT NOT NULL DEFAULT 'Apprenti'
        """
    )


    # -----------------------------------------------------
    # ACTUALITÉS
    # -----------------------------------------------------

    database.execute(
        """
        CREATE TABLE IF NOT EXISTS news (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            category TEXT NOT NULL,
            excerpt TEXT,
            content TEXT NOT NULL,
            image_name TEXT,
            status TEXT NOT NULL DEFAULT 'Brouillon',
            published_at TIMESTAMP,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )


    # -----------------------------------------------------
    # NOTIFICATIONS
    # -----------------------------------------------------

    database.execute(
        """
        CREATE TABLE IF NOT EXISTS notifications (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

            member_id INTEGER NOT NULL,

            title TEXT NOT NULL,

            message TEXT NOT NULL,

            notification_type TEXT NOT NULL
                DEFAULT 'general',

            is_read BOOLEAN NOT NULL
                DEFAULT FALSE,

            created_at TIMESTAMP NOT NULL
                DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT fk_notifications_member
                FOREIGN KEY (member_id)
                REFERENCES members(id)
                ON DELETE CASCADE
        )
        """
    )


    # -----------------------------------------------------
    # INDEX
    # -----------------------------------------------------

    database.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_notifications_member
        ON notifications(member_id)
        """
    )

    database.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_library_access_grade
        ON library_items(access_grade)
        """
    )

    database.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_news_status
        ON news(status)
        """
    )


    database.commit()


    # -----------------------------------------------------
    # DOSSIERS
    # -----------------------------------------------------

    app.config[
        "LIBRARY_FOLDER"
    ].mkdir(
        parents=True,
        exist_ok=True,
    )

    app.config[
        "NEWS_IMAGE_FOLDER"
    ].mkdir(
        parents=True,
        exist_ok=True,
    )


# =========================================================
# FONCTIONS UTILITAIRES
# =========================================================

def get_member(member_id):

    return db().execute(
        """
        SELECT *
        FROM members
        WHERE id = %s
        """,
        (member_id,),
    ).fetchone()


def is_admin():

    return (
        session.get("member_role")
        == "Administrateur"
    )


def get_member_grade_level(grade):

    return GRADE_LEVELS.get(
        (grade or "Apprenti").strip(),
        0,
    )


def has_library_access(
    member,
    required_grade,
):

    # Administrateur = accès complet
    if member["role"] == "Administrateur":
        return True

    member_level = get_member_grade_level(
        member["grade"]
    )

    required_level = GRADE_LEVELS.get(
        (required_grade or "Apprenti").strip(),
        999,
    )

    return member_level >= required_level


def get_storage_headers():

    return {
        "Authorization": (
            f"Bearer {SUPABASE_SERVICE_KEY}"
        ),
        "apikey": SUPABASE_SERVICE_KEY,
    }


def get_storage_url(filename):

    return (
        f"{SUPABASE_URL}"
        f"/storage/v1/object/"
        f"{SUPABASE_LIBRARY_BUCKET}"
        f"/{filename}"
    )


def library_content_type(extension):

    extension = (
        extension or ""
    ).lower().strip()

    if extension == "pdf":
        return "application/pdf"

    if extension == "epub":
        return "application/epub+zip"

    return "application/octet-stream"


def supabase_is_configured():

    return bool(
        SUPABASE_URL
        and SUPABASE_SERVICE_KEY
    )


# =========================================================
# AUTHENTIFICATION
# =========================================================

def login_required(view):

    @wraps(view)
    def wrapper(*args, **kwargs):

        if "member_id" not in session:

            flash(
                "Veuillez vous connecter.",
                "error",
            )

            return redirect(
                url_for("login")
            )

        return view(
            *args,
            **kwargs
        )

    return wrapper


def admin_required(view):

    @wraps(view)
    def wrapper(*args, **kwargs):

        if not is_admin():

            flash(
                "Action réservée aux administrateurs.",
                "error",
            )

            return redirect(
                url_for("dashboard")
            )

        return view(
            *args,
            **kwargs
        )

    return wrapper


# =========================================================
# ACCUEIL
# =========================================================

@app.get("/")
def home():

    news = db().execute(
        """
        SELECT *
        FROM news
        WHERE status = 'Publié'
        ORDER BY published_at DESC, created_at DESC
        LIMIT 3
        """
    ).fetchall()

    return render_template(
        "index.html",
        news=news,
    )


# =========================================================
# CONTACT
# =========================================================

@app.post("/contact")
def contact():

    values = [
        request.form.get(
            key,
            ""
        ).strip()

        for key in (
            "name",
            "email",
            "subject",
            "message",
        )
    ]

    news = db().execute(
        """
        SELECT *
        FROM news
        WHERE status = 'Publié'
        ORDER BY published_at DESC, created_at DESC
        LIMIT 3
        """
    ).fetchall()

    return render_template(
        "index.html",
        sent=all(values),
        form=request.form,
        news=news,
    )


# =========================================================
# NOTIFICATIONS
# =========================================================

@app.context_processor
def inject_notifications():
    """
    Rend les notifications disponibles dans tous les templates
    des membres.
    """

    if "member_id" not in session:
        return {
            "notifications": [],
            "unread_count": 0,
            "unread_notifications_count": 0,
        }

    database = db()

    notifications = database.execute(
        """
        SELECT
            id,
            message,
            created_at,
            is_read
        FROM notifications
        WHERE member_id = %s
        ORDER BY created_at DESC
        LIMIT 10
        """,
        (session["member_id"],),
    ).fetchall()

    result = database.execute(
        """
        SELECT COUNT(*) AS count
        FROM notifications
        WHERE member_id = %s
          AND is_read = FALSE
        """,
        (session["member_id"],),
    ).fetchone()

    unread_count = result["count"] if result else 0

    return {
        "notifications": notifications,

        # Nom utilisé éventuellement par les templates
        "unread_count": unread_count,

        # Nom actuellement utilisé par base_member.html
        "unread_notifications_count": unread_count,
    }


# =========================================================
# LIRE UNE NOTIFICATION
# =========================================================

@app.get(
    "/notification/<int:notification_id>/lire"
)
@login_required
def read_notification(notification_id):

    database = db()

    database.execute(
        """
        UPDATE notifications
        SET is_read = TRUE
        WHERE id = %s
        AND member_id = %s
        """,
        (
            notification_id,
            session["member_id"],
        ),
    )

    database.commit()

    return redirect(
        url_for("manage_meetings")
    )


# =========================================================
# PREMIÈRE INSTALLATION
# =========================================================

@app.route(
    "/setup",
    methods=["GET", "POST"]
)
def setup():

    total = db().execute(
        """
        SELECT COUNT(*) AS total
        FROM members
        """
    ).fetchone()["total"]

    if total:

        return redirect(
            url_for("login")
        )

    if request.method == "POST":

        name = request.form.get(
            "name",
            "",
        ).strip()

        email = request.form.get(
            "email",
            "",
        ).strip().lower()

        password = request.form.get(
            "password",
            "",
        )

        confirm_password = request.form.get(
            "confirm_password",
            "",
        )

        if (
            not name
            or not email
            or len(password) < 10
        ):

            flash(
                "Indiquez un nom, un e-mail et un mot de passe d'au moins 10 caractères.",
                "error",
            )

        elif password != confirm_password:

            flash(
                "Les deux mots de passe ne correspondent pas.",
                "error",
            )

        else:

            try:

                db().execute(
                    """
                    INSERT INTO members
                    (
                        name,
                        email,
                        password_hash,
                        role,
                        grade,
                        status
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        name,
                        email,
                        generate_password_hash(
                            password
                        ),
                        "Administrateur",
                        "CKS",
                        "Actif",
                    ),
                )

                db().commit()

                flash(
                    "Administrateur créé. Vous pouvez vous connecter.",
                    "success",
                )

                return redirect(
                    url_for("login")
                )

            except UniqueViolation:

                db().rollback()

                flash(
                    "Cette adresse e-mail est déjà utilisée.",
                    "error",
                )

    return render_template(
        "setup.html"
    )


# =========================================================
# CONNEXION
# =========================================================

@app.route(
    "/connexion",
    methods=["GET", "POST"]
)
def login():

    total = db().execute(
        """
        SELECT COUNT(*) AS total
        FROM members
        """
    ).fetchone()["total"]

    if not total:

        return redirect(
            url_for("setup")
        )

    if request.method == "POST":

        email = request.form.get(
            "email",
            "",
        ).strip().lower()

        password = request.form.get(
            "password",
            "",
        )

        member = db().execute(
            """
            SELECT *
            FROM members
            WHERE email = %s
            """,
            (email,),
        ).fetchone()

        if (
            member
            and member["status"] == "Actif"
            and check_password_hash(
                member["password_hash"],
                password,
            )
        ):

            session.clear()

            session.update(
                member_id=member["id"],
                member_name=member["name"],
                member_role=member["role"],
            )

            return redirect(
                url_for("dashboard")
            )

        flash(
            "Adresse e-mail, mot de passe incorrect ou compte inactif.",
            "error",
        )

    return render_template(
        "login.html"
    )


# =========================================================
# CHANGEMENT DE MOT DE PASSE
# =========================================================

@app.route(
    "/mot-de-passe",
    methods=["GET", "POST"]
)
@login_required
def change_password():

    if request.method == "POST":

        old_password = request.form.get(
            "ancien_mot_de_passe",
            "",
        )

        new_password = request.form.get(
            "nouveau_mot_de_passe",
            "",
        )

        confirmation = request.form.get(
            "confirmation",
            "",
        )

        member = db().execute(
            """
            SELECT password_hash
            FROM members
            WHERE id = %s
            """,
            (session["member_id"],),
        ).fetchone()

        if not member:

            flash(
                "Membre introuvable.",
                "error",
            )

            return redirect(
                url_for("dashboard")
            )

        if not check_password_hash(
            member["password_hash"],
            old_password,
        ):

            flash(
                "Votre ancien mot de passe est incorrect.",
                "error",
            )

            return render_template(
                "change_password.html"
            )

        if len(new_password) < 8:

            flash(
                "Le nouveau mot de passe doit contenir au moins 8 caractères.",
                "error",
            )

            return render_template(
                "change_password.html"
            )

        if new_password != confirmation:

            flash(
                "Les deux nouveaux mots de passe ne correspondent pas.",
                "error",
            )

            return render_template(
                "change_password.html"
            )

        db().execute(
            """
            UPDATE members
            SET password_hash = %s
            WHERE id = %s
            """,
            (
                generate_password_hash(
                    new_password
                ),
                session["member_id"],
            ),
        )

        db().commit()

        flash(
            "Votre mot de passe a été modifié avec succès.",
            "success",
        )

        return redirect(
            url_for("dashboard")
        )

    return render_template(
        "change_password.html"
    )


# =========================================================
# DÉCONNEXION
# =========================================================

@app.get("/deconnexion")
def logout():

    session.clear()

    return redirect(
        url_for("home")
    )


# =========================================================
# TABLEAU DE BORD
# =========================================================

@app.get("/membres")
@login_required
def dashboard():

    database = db()

    counts = {

        "members": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM members
            WHERE status = 'Actif'
            """
        ).fetchone()["total"],

        "meetings": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM meetings
            WHERE meeting_date >= %s
            """,
            (date.today().isoformat(),),
        ).fetchone()["total"],

        "documents": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM documents
            """
        ).fetchone()["total"],

        "library": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM library_items
            """
        ).fetchone()["total"],

        "news": database.execute(
            """
            SELECT COUNT(*) AS total
            FROM news
            """
        ).fetchone()["total"],
    }

    meetings = database.execute(
        """
        SELECT *
        FROM meetings
        ORDER BY meeting_date
        LIMIT 6
        """
    ).fetchall()

    documents = database.execute(
        """
        SELECT *
        FROM documents
        ORDER BY title
        LIMIT 6
        """
    ).fetchall()

    return render_template(
        "dashboard.html",
        counts=counts,
        meetings=meetings,
        documents=documents,
    )


# =========================================================
# GESTION DES MEMBRES
# =========================================================

@app.route(
    "/membres/gestion",
    methods=["GET", "POST"]
)
@login_required
@admin_required
def manage_members():

    database = db()

    if request.method == "POST":

        name = request.form.get(
            "name",
            "",
        ).strip()

        email = request.form.get(
            "email",
            "",
        ).strip().lower()

        role = request.form.get(
            "role",
            "Membre",
        ).strip()

        grade = request.form.get(
            "grade",
            "Apprenti",
        ).strip()

        password = request.form.get(
            "password",
            "",
        )

        if role not in ALLOWED_ROLES:
            role = "Membre"

        if grade not in ALLOWED_GRADES:
            grade = "Apprenti"

        if (
            not name
            or not email
            or len(password) < 8
        ):

            flash(
                "Indiquez le nom, l'e-mail et un mot de passe d'au moins 8 caractères.",
                "error",
            )

        else:

            try:

                database.execute(
                    """
                    INSERT INTO members
                    (
                        name,
                        email,
                        password_hash,
                        role,
                        grade,
                        status
                    )
                    VALUES (%s, %s, %s, %s, %s, %s)
                    """,
                    (
                        name,
                        email,
                        generate_password_hash(
                            password
                        ),
                        role,
                        grade,
                        "Actif",
                    ),
                )

                database.commit()

                flash(
                    "Membre ajouté avec succès.",
                    "success",
                )

            except UniqueViolation:

                database.rollback()

                flash(
                    "Cette adresse e-mail est déjà utilisée.",
                    "error",
                )

    search = request.args.get(
        "q",
        "",
    ).strip()

    if search:

        pattern = f"%{search}%"

        members = database.execute(
            """
            SELECT
                id,
                name,
                email,
                role,
                grade,
                status
            FROM members
            WHERE name ILIKE %s
               OR email ILIKE %s
            ORDER BY name
            """,
            (
                pattern,
                pattern,
            ),
        ).fetchall()

    else:

        members = database.execute(
            """
            SELECT
                id,
                name,
                email,
                role,
                grade,
                status
            FROM members
            ORDER BY name
            """
        ).fetchall()

    return render_template(
        "members.html",
        members=members,
        search=search,
    )


# =========================================================
# DÉTAIL D'UN MEMBRE
# =========================================================

@app.get("/membres/<int:member_id>")
@login_required
@admin_required
def member_detail(member_id):

    member = db().execute(
        """
        SELECT
            id,
            name,
            email,
            role,
            grade,
            status
        FROM members
        WHERE id = %s
        """,
        (member_id,),
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    return render_template(
        "member_detail.html",
        member=member,
    )


# =========================================================
# ACTIVATION / DÉSACTIVATION
# =========================================================

@app.post(
    "/membres/<int:member_id>/statut"
)
@login_required
@admin_required
def toggle_member_status(member_id):

    database = db()

    member = database.execute(
        """
        SELECT id, status
        FROM members
        WHERE id = %s
        """,
        (member_id,),
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    if member_id == session["member_id"]:

        flash(
            "Vous ne pouvez pas désactiver votre propre compte.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    new_status = (
        "Inactif"
        if member["status"] == "Actif"
        else "Actif"
    )

    database.execute(
        """
        UPDATE members
        SET status = %s
        WHERE id = %s
        """,
        (
            new_status,
            member_id,
        ),
    )

    database.commit()

    flash(
        "Statut du membre mis à jour.",
        "success",
    )

    return redirect(
        url_for("manage_members")
    )


# =========================================================
# MODIFICATION DU GRADE
# =========================================================

@app.post(
    "/membres/<int:member_id>/grade"
)
@login_required
@admin_required
def update_member_grade(member_id):

    grade = request.form.get(
        "grade",
        "Apprenti",
    ).strip()

    if grade not in ALLOWED_GRADES:

        flash(
            "Grade invalide.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    database = db()

    member = database.execute(
        """
        SELECT id
        FROM members
        WHERE id = %s
        """,
        (member_id,),
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    database.execute(
        """
        UPDATE members
        SET grade = %s
        WHERE id = %s
        """,
        (
            grade,
            member_id,
        ),
    )

    database.commit()

    flash(
        "Grade du membre mis à jour.",
        "success",
    )

    return redirect(
        url_for("manage_members")
    )


# =========================================================
# MODIFICATION DE LA FONCTION
# =========================================================

@app.post(
    "/membres/<int:member_id>/fonction"
)
@login_required
@admin_required
def update_member_role(member_id):

    role = request.form.get(
        "role",
        "Membre",
    ).strip()

    if role not in ALLOWED_ROLES:

        flash(
            "Fonction invalide.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    database = db()

    member = database.execute(
        """
        SELECT id
        FROM members
        WHERE id = %s
        """,
        (member_id,),
    ).fetchone()

    if member is None:

        flash(
            "Membre introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_members")
        )

    database.execute(
        """
        UPDATE members
        SET role = %s
        WHERE id = %s
        """,
        (
            role,
            member_id,
        ),
    )

    database.commit()

    flash(
        "Fonction du membre modifiée avec succès.",
        "success",
    )

    return redirect(
        url_for("manage_members")
    )


# =========================================================
# RÉUNIONS
# =========================================================

@app.route(
    "/reunions",
    methods=["GET", "POST"]
)
@login_required
def manage_meetings():

    if request.method == "POST":

        if not is_admin():

            flash(
                "Seuls les administrateurs peuvent créer une réunion.",
                "error",
            )

            return redirect(
                url_for("manage_meetings")
            )

        title = request.form.get(
            "title",
            "",
        ).strip()

        meeting_date = request.form.get(
            "meeting_date",
            "",
        ).strip()

        location = request.form.get(
            "location",
            "",
        ).strip()

        notes = request.form.get(
            "notes",
            "",
        ).strip()

        if (
            not title
            or not meeting_date
            or not location
        ):

            flash(
                "Veuillez remplir tous les champs obligatoires.",
                "error",
            )

        else:

            database = db()

            try:

                database.execute(
                    """
                    INSERT INTO meetings
                    (
                        title,
                        meeting_date,
                        location,
                        notes
                    )
                    VALUES (%s, %s, %s, %s)
                    """,
                    (
                        title,
                        meeting_date,
                        location,
                        notes,
                    ),
                )

                database.execute(
                    """
                    INSERT INTO notifications
                    (
                        member_id,
                        title,
                        message,
                        notification_type
                    )
                    SELECT
                        id,
                        %s,
                        %s,
                        %s
                    FROM members
                    WHERE status = 'Actif'
                    """,
                    (
                        "Nouvelle réunion",
                        (
                            f"Une nouvelle réunion a été programmée : "
                            f"{title} le {meeting_date} "
                            f"à {location}."
                        ),
                        "meeting",
                    ),
                )

                database.commit()

                flash(
                    "Réunion enregistrée et notifications envoyées.",
                    "success",
                )

            except Exception:

                database.rollback()

                app.logger.exception(
                    "Erreur lors de la création de la réunion."
                )

                flash(
                    "Impossible d'enregistrer la réunion.",
                    "error",
                )

    meetings = db().execute(
        """
        SELECT *
        FROM meetings
        ORDER BY meeting_date DESC
        """
    ).fetchall()

    return render_template(
        "meetings.html",
        meetings=meetings,
    )


# =========================================================
# MODIFIER UNE RÉUNION
# =========================================================

@app.route(
    "/reunion/<int:meeting_id>/modifier",
    methods=["GET", "POST"]
)
@login_required
@admin_required
def edit_meeting(meeting_id):

    database = db()

    meeting = database.execute(
        """
        SELECT *
        FROM meetings
        WHERE id = %s
        """,
        (meeting_id,),
    ).fetchone()

    if meeting is None:

        flash(
            "Réunion introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_meetings")
        )

    if request.method == "POST":

        title = request.form.get(
            "title",
            "",
        ).strip()

        meeting_date = request.form.get(
            "meeting_date",
            "",
        ).strip()

        location = request.form.get(
            "location",
            "",
        ).strip()

        notes = request.form.get(
            "notes",
            "",
        ).strip()

        if (
            not title
            or not meeting_date
            or not location
        ):

            flash(
                "Veuillez remplir tous les champs obligatoires.",
                "error",
            )

            return render_template(
                "edit_meeting.html",
                meeting=meeting,
            )

        database.execute(
            """
            UPDATE meetings
            SET
                title = %s,
                meeting_date = %s,
                location = %s,
                notes = %s
            WHERE id = %s
            """,
            (
                title,
                meeting_date,
                location,
                notes,
                meeting_id,
            ),
        )

        database.commit()

        flash(
            "Réunion modifiée avec succès.",
            "success",
        )

        return redirect(
            url_for("manage_meetings")
        )

    return render_template(
        "edit_meeting.html",
        meeting=meeting,
    )


# =========================================================
# SUPPRIMER UNE RÉUNION
# =========================================================

@app.post(
    "/reunion/<int:meeting_id>/supprimer"
)
@login_required
@admin_required
def delete_meeting(meeting_id):

    database = db()

    meeting = database.execute(
        """
        SELECT id
        FROM meetings
        WHERE id = %s
        """,
        (meeting_id,),
    ).fetchone()

    if meeting is None:

        flash(
            "Réunion introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_meetings")
        )

    database.execute(
        """
        DELETE FROM meetings
        WHERE id = %s
        """,
        (meeting_id,),
    )

    database.commit()

    flash(
        "Réunion supprimée avec succès.",
        "success",
    )

    return redirect(
        url_for("manage_meetings")
    )

# =========================================================
# DOCUMENTS
# =========================================================

@app.route(
    "/documents",
    methods=["GET", "POST"]
)
@login_required
def manage_documents():

    # -----------------------------------------------------
    # AJOUTER UN DOCUMENT
    # -----------------------------------------------------

    if request.method == "POST":

        if not is_admin():
            flash(
                "Seuls les administrateurs peuvent ajouter des documents.",
                "error",
            )
            return redirect(
                url_for("manage_documents")
            )

        title = request.form.get(
            "title",
            "",
        ).strip()

        category = request.form.get(
            "category",
            "",
        ).strip()

        reference = request.form.get(
            "reference",
            "",
        ).strip()

        if not title or not category or not reference:

            flash(
                "Tous les champs sont obligatoires.",
                "error",
            )

        else:

            database = db()

            database.execute(
                """
                INSERT INTO documents
                (
                    title,
                    category,
                    reference
                )
                VALUES (%s, %s, %s)
                """,
                (
                    title,
                    category,
                    reference,
                ),
            )

            database.commit()

            flash(
                "Document ajouté avec succès.",
                "success",
            )

        return redirect(
            url_for("manage_documents")
        )

    # -----------------------------------------------------
    # LISTE DES DOCUMENTS
    # -----------------------------------------------------

    documents = db().execute(
        """
        SELECT
            id,
            title,
            category,
            reference
        FROM documents
        ORDER BY title
        """
    ).fetchall()

    return render_template(
        "documents.html",
        documents=documents,
    )


# =========================================================
# MODIFIER UN DOCUMENT
# =========================================================

@app.route(
    "/documents/<int:document_id>/modifier",
    methods=["GET", "POST"]
)
@admin_required
def edit_document(document_id):

    database = db()

    # -----------------------------------------------------
    # RÉCUPÉRER LE DOCUMENT
    # -----------------------------------------------------

    document = database.execute(
        """
        SELECT
            id,
            title,
            category,
            reference
        FROM documents
        WHERE id = %s
        """,
        (document_id,),
    ).fetchone()

    if not document:

        flash(
            "Document introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_documents")
        )

    # -----------------------------------------------------
    # MODIFICATION
    # -----------------------------------------------------

    if request.method == "POST":

        title = request.form.get(
            "title",
            "",
        ).strip()

        category = request.form.get(
            "category",
            "",
        ).strip()

        reference = request.form.get(
            "reference",
            "",
        ).strip()

        if not title or not category or not reference:

            flash(
                "Tous les champs sont obligatoires.",
                "error",
            )

            return render_template(
                "document_modifier.html",
                document=document,
            )

        database.execute(
            """
            UPDATE documents
            SET
                title = %s,
                category = %s,
                reference = %s
            WHERE id = %s
            """,
            (
                title,
                category,
                reference,
                document_id,
            ),
        )

        database.commit()

        flash(
            "Document modifié avec succès.",
            "success",
        )

        return redirect(
            url_for("manage_documents")
        )

    return render_template(
        "document_modifier.html",
        document=document,
    )


# =========================================================
# SUPPRIMER UN DOCUMENT
# =========================================================

@app.post(
    "/documents/<int:document_id>/supprimer"
)
@admin_required
def delete_document(document_id):

    database = db()

    document = database.execute(
        """
        SELECT
            id,
            title
        FROM documents
        WHERE id = %s
        """,
        (document_id,),
    ).fetchone()

    if not document:

        flash(
            "Document introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_documents")
        )

    database.execute(
        """
        DELETE FROM documents
        WHERE id = %s
        """,
        (document_id,),
    )

    database.commit()

    flash(
        f"Le document « {document['title']} » a été supprimé.",
        "success",
    )

    return redirect(
        url_for("manage_documents")
    )

# =========================================================
# GESTION DES ACTUALITÉS
# =========================================================

@app.route(
    "/admin/actualites",
    methods=["GET", "POST"]
)
@login_required
@admin_required
def manage_news():

    database = db()

    if request.method == "POST":

        title = request.form.get(
            "title",
            "",
        ).strip()

        category = request.form.get(
            "category",
            "",
        ).strip()

        excerpt = request.form.get(
            "excerpt",
            "",
        ).strip()

        content = request.form.get(
            "content",
            "",
        ).strip()

        status = request.form.get(
            "status",
            "Brouillon",
        ).strip()

        if status not in (
            "Brouillon",
            "Publié",
        ):
            status = "Brouillon"

        if (
            not title
            or not category
            or not content
        ):

            flash(
                "Le titre, la catégorie et le contenu sont obligatoires.",
                "error",
            )

            return redirect(
                url_for("manage_news")
            )

        image = request.files.get(
            "image"
        )

        image_name = None
        image_path = None

        # -------------------------------------------------
        # IMAGE
        # -------------------------------------------------

        if image and image.filename:

            original_name = secure_filename(
                image.filename
            )

            if (
                not original_name
                or "." not in original_name
            ):

                flash(
                    "Nom de fichier image invalide.",
                    "error",
                )

                return redirect(
                    url_for("manage_news")
                )

            extension = (
                original_name
                .rsplit(".", 1)[-1]
                .lower()
            )

            if extension not in ALLOWED_NEWS_IMAGE_EXTENSIONS:

                flash(
                    "Format d'image non autorisé.",
                    "error",
                )

                return redirect(
                    url_for("manage_news")
                )

            image_name = (
                f"{uuid.uuid4().hex}.{extension}"
            )

            image_folder = app.config[
                "NEWS_IMAGE_FOLDER"
            ]

            image_folder.mkdir(
                parents=True,
                exist_ok=True,
            )

            image_path = (
                image_folder
                / image_name
            )

            image.save(image_path)

        published_at = (
            datetime.now()
            if status == "Publié"
            else None
        )

        try:

            database.execute(
                """
                INSERT INTO news
                (
                    title,
                    category,
                    excerpt,
                    content,
                    image_name,
                    status,
                    published_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    title,
                    category,
                    excerpt,
                    content,
                    image_name,
                    status,
                    published_at,
                ),
            )

            database.commit()

        except Exception:

            database.rollback()

            if (
                image_path
                and image_path.exists()
            ):
                image_path.unlink()

            app.logger.exception(
                "Erreur lors de la création de l'actualité."
            )

            flash(
                "Impossible d'enregistrer l'actualité.",
                "error",
            )

            return redirect(
                url_for("manage_news")
            )

        flash(
            "Actualité enregistrée avec succès.",
            "success",
        )

        return redirect(
            url_for("manage_news")
        )

    news = database.execute(
        """
        SELECT *
        FROM news
        ORDER BY created_at DESC
        """
    ).fetchall()

    return render_template(
        "news_admin.html",
        news=news,
    )


# =========================================================
# MODIFIER UNE ACTUALITÉ
# =========================================================

@app.route(
    "/admin/actualites/modifier/<int:news_id>",
    methods=["GET", "POST"]
)
@login_required
@admin_required
def edit_news(news_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM news
        WHERE id = %s
        """,
        (news_id,),
    ).fetchone()

    if item is None:

        flash(
            "Actualité introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_news")
        )

    if request.method == "POST":

        title = request.form.get(
            "title",
            "",
        ).strip()

        category = request.form.get(
            "category",
            "",
        ).strip()

        excerpt = request.form.get(
            "excerpt",
            "",
        ).strip()

        content = request.form.get(
            "content",
            "",
        ).strip()

        status = request.form.get(
            "status",
            "Brouillon",
        ).strip()

        if status not in (
            "Brouillon",
            "Publié",
        ):
            status = "Brouillon"

        if (
            not title
            or not category
            or not content
        ):

            flash(
                "Le titre, la catégorie et le contenu sont obligatoires.",
                "error",
            )

            return redirect(
                url_for(
                    "edit_news",
                    news_id=news_id,
                )
            )

        published_at = (
            item["published_at"]
            or datetime.now()
        ) if status == "Publié" else None

        image = request.files.get(
            "image"
        )

        new_image_name = item[
            "image_name"
        ]

        new_image_path = None

        # -------------------------------------------------
        # NOUVELLE IMAGE
        # -------------------------------------------------

        if image and image.filename:

            original_name = secure_filename(
                image.filename
            )

            if (
                not original_name
                or "." not in original_name
            ):

                flash(
                    "Nom de fichier image invalide.",
                    "error",
                )

                return redirect(
                    url_for(
                        "edit_news",
                        news_id=news_id,
                    )
                )

            extension = (
                original_name
                .rsplit(".", 1)[-1]
                .lower()
            )

            if extension not in ALLOWED_NEWS_IMAGE_EXTENSIONS:

                flash(
                    "Format d'image non autorisé.",
                    "error",
                )

                return redirect(
                    url_for(
                        "edit_news",
                        news_id=news_id,
                    )
                )

            new_image_name = (
                f"{uuid.uuid4().hex}.{extension}"
            )

            image_folder = app.config[
                "NEWS_IMAGE_FOLDER"
            ]

            image_folder.mkdir(
                parents=True,
                exist_ok=True,
            )

            new_image_path = (
                image_folder
                / new_image_name
            )

            image.save(new_image_path)

        try:

            database.execute(
                """
                UPDATE news
                SET
                    title = %s,
                    category = %s,
                    excerpt = %s,
                    content = %s,
                    image_name = %s,
                    status = %s,
                    published_at = %s,
                    updated_at = CURRENT_TIMESTAMP
                WHERE id = %s
                """,
                (
                    title,
                    category,
                    excerpt,
                    content,
                    new_image_name,
                    status,
                    published_at,
                    news_id,
                ),
            )

            database.commit()

        except Exception:

            database.rollback()

            if (
                new_image_path
                and new_image_path.exists()
            ):
                new_image_path.unlink()

            app.logger.exception(
                "Erreur lors de la modification de l'actualité."
            )

            flash(
                "Impossible de modifier l'actualité.",
                "error",
            )

            return redirect(
                url_for(
                    "edit_news",
                    news_id=news_id,
                )
            )

        # -------------------------------------------------
        # SUPPRESSION DE L'ANCIENNE IMAGE
        # -------------------------------------------------

        if (
            new_image_path
            and item["image_name"]
            and item["image_name"]
            != new_image_name
        ):

            old_path = (
                app.config[
                    "NEWS_IMAGE_FOLDER"
                ]
                / item["image_name"]
            )

            if old_path.exists():
                old_path.unlink()

        flash(
            "Actualité modifiée avec succès.",
            "success",
        )

        return redirect(
            url_for("manage_news")
        )

    return render_template(
        "news_edit.html",
        item=item,
    )


# =========================================================
# SUPPRIMER UNE ACTUALITÉ
# =========================================================

@app.post(
    "/admin/actualites/supprimer/<int:news_id>"
)
@login_required
@admin_required
def delete_news(news_id):

    database = db()

    item = database.execute(
        """
        SELECT image_name
        FROM news
        WHERE id = %s
        """,
        (news_id,),
    ).fetchone()

    if item is None:

        flash(
            "Actualité introuvable.",
            "error",
        )

        return redirect(
            url_for("manage_news")
        )

    database.execute(
        """
        DELETE FROM news
        WHERE id = %s
        """,
        (news_id,),
    )

    database.commit()

    if item["image_name"]:

        image_path = (
            app.config[
                "NEWS_IMAGE_FOLDER"
            ]
            / item["image_name"]
        )

        if image_path.exists():
            image_path.unlink()

    flash(
        "Actualité supprimée avec succès.",
        "success",
    )

    return redirect(
        url_for("manage_news")
    )


# =========================================================
# ACTUALITÉS PUBLIQUES
# =========================================================

@app.get("/actualites")
def public_news():

    news = db().execute(
        """
        SELECT *
        FROM news
        WHERE status = 'Publié'
        ORDER BY published_at DESC, created_at DESC
        """
    ).fetchall()

    return render_template(
        "news.html",
        news=news,
    )


# =========================================================
# IMAGE D'UNE ACTUALITÉ
# =========================================================

@app.get(
    "/actualites/image/<path:filename>"
)
def news_image(filename):

    return send_from_directory(
        app.config["NEWS_IMAGE_FOLDER"],
        filename,
        as_attachment=False,
    )


# =========================================================
# DÉTAIL D'UNE ACTUALITÉ
# =========================================================

@app.get(
    "/actualites/<int:news_id>"
)
def news_detail(news_id):

    item = db().execute(
        """
        SELECT *
        FROM news
        WHERE id = %s
        AND status = 'Publié'
        """,
        (news_id,),
    ).fetchone()

    if item is None:

        return render_template(
            "news_not_found.html"
        ), 404

    return render_template(
        "news_detail.html",
        item=item,
    )


# =========================================================
# BIBLIOTHÈQUE
# =========================================================

@app.route(
    "/bibliotheque",
    methods=["GET", "POST"]
)
@login_required
def library():

    database = db()

    # =====================================================
    # AJOUT D'UN OUVRAGE
    # =====================================================

    if request.method == "POST":

        if not is_admin():

            flash(
                "Seuls les administrateurs peuvent ajouter des ouvrages.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        if not supabase_is_configured():

            flash(
                "Le stockage Supabase n'est pas configuré.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        uploaded = request.files.get(
            "file"
        )

        title = request.form.get(
            "title",
            "",
        ).strip()

        author = request.form.get(
            "author",
            "",
        ).strip()

        category = request.form.get(
            "category",
            "",
        ).strip()

        description = request.form.get(
            "description",
            "",
        ).strip()

        access_grade = request.form.get(
            "access_grade",
            "Apprenti",
        ).strip()

        # -------------------------------------------------
        # VALIDATION DU GRADE
        # -------------------------------------------------

        if access_grade not in ALLOWED_GRADES:

            flash(
                "Niveau d'accès invalide.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        # -------------------------------------------------
        # VALIDATION
        # -------------------------------------------------

        if not title or not category:

            flash(
                "Le titre et la catégorie sont obligatoires.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        if not uploaded or not uploaded.filename:

            flash(
                "Veuillez sélectionner un fichier.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        original_name = secure_filename(
            uploaded.filename
        )

        if (
            not original_name
            or "." not in original_name
        ):

            flash(
                "Nom de fichier invalide.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        extension = (
            original_name
            .rsplit(".", 1)[-1]
            .lower()
        )

        if extension not in ALLOWED_LIBRARY_EXTENSIONS:

            flash(
                "Format non autorisé. Utilisez uniquement PDF ou EPUB.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        # -------------------------------------------------
        # NOM UNIQUE
        # -------------------------------------------------

        stored_name = (
            f"{uuid.uuid4().hex}.{extension}"
        )

        try:

            uploaded.stream.seek(0)

            file_data = uploaded.read()

            if not file_data:

                flash(
                    "Le fichier envoyé est vide.",
                    "error",
                )

                return redirect(
                    url_for("library")
                )

            content_type = library_content_type(
                extension
            )

            storage_url = get_storage_url(
                stored_name
            )

            headers = get_storage_headers()

            headers["Content-Type"] = (
                content_type
            )

            # -------------------------------------------------
            # UPLOAD SUPABASE
            # -------------------------------------------------

            response = httpx.post(
                storage_url,
                headers=headers,
                content=file_data,
                timeout=120.0,
            )

            if response.status_code not in (
                200,
                201,
            ):

                app.logger.error(
                    "Supabase upload %s : %s",
                    response.status_code,
                    response.text[:500],
                )

                flash(
                    "Impossible d'envoyer le fichier vers Supabase.",
                    "error",
                )

                return redirect(
                    url_for("library")
                )

            # -------------------------------------------------
            # ENREGISTREMENT POSTGRESQL
            # -------------------------------------------------

            try:

                database.execute(
                    """
                    INSERT INTO library_items
                    (
                        title,
                        author,
                        category,
                        description,
                        stored_name,
                        original_name,
                        file_extension,
                        access_grade
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                    """,
                    (
                        title,
                        author,
                        category,
                        description,
                        stored_name,
                        original_name,
                        extension,
                        access_grade,
                    ),
                )

                database.commit()

            except Exception:

                database.rollback()

                # Supprimer le fichier de Supabase
                # si PostgreSQL échoue.

                try:

                    httpx.delete(
                        storage_url,
                        headers=get_storage_headers(),
                        timeout=30.0,
                    )

                except Exception:

                    app.logger.exception(
                        "Impossible de supprimer le fichier Supabase après échec PostgreSQL."
                    )

                raise

            flash(
                "Ouvrage ajouté avec succès.",
                "success",
            )

        except Exception:

            app.logger.exception(
                "Erreur lors de l'ajout de l'ouvrage."
            )

            flash(
                "Une erreur est survenue lors de l'ajout de l'ouvrage.",
                "error",
            )

        return redirect(
            url_for("library")
        )

    # =====================================================
    # RECHERCHE
    # =====================================================

    search = request.args.get(
        "q",
        "",
    ).strip()

    if search:

        pattern = f"%{search}%"

        items = database.execute(
            """
            SELECT *
            FROM library_items
            WHERE
                title ILIKE %s
                OR author ILIKE %s
                OR category ILIKE %s
                OR description ILIKE %s
            ORDER BY added_at DESC
            """,
            (
                pattern,
                pattern,
                pattern,
                pattern,
            ),
        ).fetchall()

    else:

        items = database.execute(
            """
            SELECT *
            FROM library_items
            ORDER BY added_at DESC
            """
        ).fetchall()

    return render_template(
        "library.html",
        items=items,
        search=search,
    )


# =========================================================
# MODIFIER LE GRADE D'ACCÈS D'UN OUVRAGE
# =========================================================

@app.post(
    "/bibliotheque/modifier-acces/<int:item_id>"
)
@login_required
@admin_required
def update_library_access(item_id):

    access_grade = request.form.get(
        "access_grade",
        "Apprenti",
    ).strip()

    if access_grade not in ALLOWED_GRADES:

        flash(
            "Niveau d'accès invalide.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    database = db()

    item = database.execute(
        """
        SELECT id
        FROM library_items
        WHERE id = %s
        """,
        (item_id,),
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    database.execute(
        """
        UPDATE library_items
        SET access_grade = %s
        WHERE id = %s
        """,
        (
            access_grade,
            item_id,
        ),
    )

    database.commit()

    flash(
        "Niveau d'accès de l'ouvrage modifié avec succès.",
        "success",
    )

    return redirect(
        url_for("library")
    )


# =========================================================
# LECTURE D'UN OUVRAGE
# =========================================================

@app.get(
    "/bibliotheque/lire/<int:item_id>"
)
@login_required
def read_library_item(item_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM library_items
        WHERE id = %s
        """,
        (item_id,),
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    member = get_member(
        session["member_id"]
    )

    if member is None:

        session.clear()

        flash(
            "Votre session n'est plus valide.",
            "error",
        )

        return redirect(
            url_for("login")
        )

    # -----------------------------------------------------
    # CONTRÔLE DU GRADE
    # -----------------------------------------------------

    if not has_library_access(
        member,
        item["access_grade"],
    ):

        flash(
            "Cet ouvrage est réservé à un grade supérieur.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    return render_template(
        "library_reader.html",
        item=item,
    )


# =========================================================
# FICHIER PRIVÉ — LECTURE
# =========================================================

@app.get(
    "/bibliotheque/fichier/<int:item_id>"
)
@login_required
def library_file(item_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM library_items
        WHERE id = %s
        """,
        (item_id,),
    ).fetchone()

    if item is None:

        return "Ouvrage introuvable.", 404

    member = get_member(
        session["member_id"]
    )

    if member is None:

        session.clear()

        return "Session invalide.", 401

    # -----------------------------------------------------
    # CONTRÔLE DU GRADE
    # -----------------------------------------------------

    if not has_library_access(
        member,
        item["access_grade"],
    ):

        return (
            "Accès refusé : grade insuffisant.",
            403,
        )

    if not supabase_is_configured():

        app.logger.error(
            "Supabase n'est pas configuré."
        )

        return (
            "Stockage de la bibliothèque non configuré.",
            500,
        )

    storage_url = get_storage_url(
        item["stored_name"]
    )

    try:

        response = httpx.get(
            storage_url,
            headers=get_storage_headers(),
            timeout=120.0,
        )

        if response.status_code != 200:

            app.logger.error(
                "Supabase download HTTP %s : %s",
                response.status_code,
                response.text[:500],
            )

            return (
                "Impossible de charger cet ouvrage.",
                500,
            )

        content_type = library_content_type(
            item["file_extension"]
        )

        return Response(
            response.content,
            mimetype=content_type,
            headers={
                "Content-Disposition": (
                    f'inline; filename="{item["original_name"]}"'
                ),
                "Cache-Control": (
                    "private, no-store"
                ),
            },
        )

    except Exception:

        app.logger.exception(
            "Erreur lors de la lecture depuis Supabase."
        )

        return (
            "Impossible de charger cet ouvrage.",
            500,
        )


# =========================================================
# TÉLÉCHARGEMENT D'UN OUVRAGE
# =========================================================

@app.get(
    "/bibliotheque/telecharger/<int:item_id>"
)
@login_required
def download_library_item(item_id):

    database = db()

    item = database.execute(
        """
        SELECT *
        FROM library_items
        WHERE id = %s
        """,
        (item_id,),
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    member = get_member(
        session["member_id"]
    )

    if member is None:

        session.clear()

        return redirect(
            url_for("login")
        )

    # -----------------------------------------------------
    # CONTRÔLE DU GRADE
    # -----------------------------------------------------

    if not has_library_access(
        member,
        item["access_grade"],
    ):

        flash(
            "Cet ouvrage est réservé à un grade supérieur.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    if not supabase_is_configured():

        flash(
            "Le stockage de la bibliothèque n'est pas configuré.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    storage_url = get_storage_url(
        item["stored_name"]
    )

    try:

        response = httpx.get(
            storage_url,
            headers=get_storage_headers(),
            timeout=120.0,
        )

        if response.status_code != 200:

            app.logger.error(
                "Supabase download HTTP %s : %s",
                response.status_code,
                response.text[:500],
            )

            flash(
                "Impossible de télécharger cet ouvrage.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        content_type = library_content_type(
            item["file_extension"]
        )

        return Response(
            response.content,
            mimetype=content_type,
            headers={
                "Content-Disposition": (
                    f'attachment; filename="{item["original_name"]}"'
                ),
                "Cache-Control": (
                    "private, no-store"
                ),
            },
        )

    except Exception:

        app.logger.exception(
            "Erreur lors du téléchargement depuis Supabase."
        )

        flash(
            "Impossible de télécharger cet ouvrage.",
            "error",
        )

        return redirect(
            url_for("library")
        )


# =========================================================
# SUPPRIMER UN OUVRAGE
# =========================================================

@app.post(
    "/bibliotheque/supprimer/<int:item_id>"
)
@login_required
@admin_required
def delete_library_item(item_id):

    database = db()

    item = database.execute(
        """
        SELECT stored_name
        FROM library_items
        WHERE id = %s
        """,
        (item_id,),
    ).fetchone()

    if item is None:

        flash(
            "Ouvrage introuvable.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    if not supabase_is_configured():

        flash(
            "Le stockage Supabase n'est pas configuré.",
            "error",
        )

        return redirect(
            url_for("library")
        )

    storage_url = get_storage_url(
        item["stored_name"]
    )

    try:

        response = httpx.delete(
            storage_url,
            headers=get_storage_headers(),
            timeout=60.0,
        )

        if response.status_code not in (
            200,
            204,
        ):

            app.logger.error(
                "Erreur suppression Supabase HTTP %s : %s",
                response.status_code,
                response.text[:500],
            )

            flash(
                "Impossible de supprimer le fichier de Supabase.",
                "error",
            )

            return redirect(
                url_for("library")
            )

        database.execute(
            """
            DELETE FROM library_items
            WHERE id = %s
            """,
            (item_id,),
        )

        database.commit()

        flash(
            "Ouvrage supprimé de la bibliothèque.",
            "success",
        )

    except Exception:

        database.rollback()

        app.logger.exception(
            "Erreur lors de la suppression de l'ouvrage."
        )

        flash(
            "Une erreur est survenue lors de la suppression.",
            "error",
        )

    return redirect(
        url_for("library")
    )


# =========================================================
# LANCEMENT
# =========================================================

if __name__ == "__main__":

    app.run(
        debug=True
    )